/*
	Base Tables
	User Table
	Rahul
*/

create table USER_DATA (
ID NUMBER(20) NOT NULL,
USER_IDENTIFIER VARCHAR2(255) NOT NULL,
INVALID_LOGIN_ATTEMPT NUMBER(11),
LAST_LOGIN_ATTEMPT_TIME TIMESTAMP(6), 
LAST_LOGIN_TIME TIMESTAMP(6),
LAST_PASSWORD_CHANGE_TIME TIMESTAMP(6),
OWNER_USER_ID NUMBER(20),
CREATED_BY VARCHAR2(255),
CREATED_DATE TIMESTAMP(6),
DELETED NUMBER(1),
UPDATED_BY VARCHAR2(255),
UPDATED_DATE TIMESTAMP(6),
PRIMARY KEY ("ID")
)
/

create table USER_PASSWORD (
ID NUMBER(20) NOT NULL,
USER_ID NUMBER(20) NOT NULL,
PASSWORD VARCHAR2(255),
PRIMARY KEY ("ID"),
	 FOREIGN KEY ("USER_ID") REFERENCES  "USER_DATA" ("ID")
)

/

create table USER_PROFILE (
ID NUMBER(20) NOT NULL,
USER_ID NUMBER(20) NOT NULL,
PRIMARY KEY ("ID"),
	 FOREIGN KEY ("USER_ID") REFERENCES  "USER_DATA" ("ID")
)

/

create table USER_PROFILE_ROLE (
ID NUMBER(20) NOT NULL,
USER_PROFILE_ID NUMBER(20) NOT NULL,
ROLE_NAME VARCHAR2(50),
PRIMARY KEY ("ID"),
	 FOREIGN KEY ("USER_PROFILE_ID") REFERENCES  "USER_PROFILE" ("ID")
)


/
COMMIT
/

--//@UNDO

DROP TABLE USER_PROFILE_ROLE
/
DROP TABLE USER_PROFILE
/
DROP TABLE USER_PASSWORD
/
DROP TABLE USER_DATA
/