/*
	Base Tables
	User Table
	Rahul
*/

create table USER_DATA (
ID NUMBER(20) NOT NULL,
USER_IDENTIFIER VARCHAR2(255) NOT NULL,
INVALID_LOGIN_ATTEMPT NUMBER(11),
LAST_LOGIN_ATTEMPT_TIME TIMESTAMP(6), 
LAST_LOGIN_TIME TIMESTAMP(6),
LAST_PASSWORD_CHANGE_TIME TIMESTAMP(6),
OWNER_USER_ID NUMBER(20),
CREATED_BY VARCHAR2(255),
CREATED_DATE TIMESTAMP(6),
DELETED NUMBER(1),
UPDATED_BY VARCHAR2(255),
UPDATED_DATE TIMESTAMP(6)
)

/
COMMIT
/

--//@UNDO

DROP TABLE USER_DATA
/