/*
	Base Tables
	Individual Table
	Rahul
*/

create table INDIVIDUAL (
ID NUMBER(20) NOT NULL,
OWNER_USER_ID NUMBER(20),
CREATED_BY VARCHAR2(255),
CREATED_DATE TIMESTAMP(6),
DELETED NUMBER(1),
UPDATED_BY VARCHAR2(255),
UPDATED_DATE TIMESTAMP(6),
USER_ID VARCHAR2(255),
ADDRESS_ID NUMBER(20),
PRIMARY KEY ("ID"),
	 FOREIGN KEY ("ADDRESS_ID") REFERENCES  "ADDRESS" ("ID")
)


/
COMMIT
/

--//@UNDO

DROP TABLE INDIVIDUAL
/