/*
	Base Tables
	Common Table
	Rahul
*/

create table ADDRESS (
ID NUMBER(20) NOT NULL,
OWNER_USER_ID NUMBER(20),
CREATED_BY VARCHAR2(100),
CREATED_DATE TIMESTAMP(6),
DELETED NUMBER(1),
UPDATED_BY VARCHAR2(100),
UPDATED_DATE TIMESTAMP(6),
CITY VARCHAR2(100),
STATE_CODE VARCHAR2(100),
ZIP_CODE varchar2(100),
	PRIMARY KEY ("ID")
)
/

create table LOCATION (
ID NUMBER(20) NOT NULL,
OWNER_USER_ID NUMBER(20),
CREATED_BY VARCHAR2(100),
CREATED_DATE TIMESTAMP(6),
DELETED NUMBER(1),
UPDATED_BY VARCHAR2(100),
UPDATED_DATE TIMESTAMP(6),
CITY VARCHAR2(100),
STATE_CODE VARCHAR2(100),
	PRIMARY KEY ("ID")
)
/

CREATE TABLE CAR_BRAND (
ID NUMBER(20) NOT NULL,
OWNER_USER_ID NUMBER(20),
CREATED_BY VARCHAR2(100),
CREATED_DATE TIMESTAMP(6),
DELETED NUMBER(1),
UPDATED_BY VARCHAR2(100),
UPDATED_DATE TIMESTAMP(6),
BRAND_NAME VARCHAR2(255),
	PRIMARY KEY ("ID")
)
/

CREATE TABLE CAR (
ID NUMBER(20) NOT NULL,
OWNER_USER_ID NUMBER(20),
CREATED_BY VARCHAR2(100),
CREATED_DATE TIMESTAMP(6),
DELETED NUMBER(1),
UPDATED_BY VARCHAR2(100),
UPDATED_DATE TIMESTAMP(6),
CAR_BRAND_ID NUMBER(20),
CAR_NAME VARCHAR2(255),
CAR_MODEL VARCHAR2(255),
	PRIMARY KEY ("ID"),
	FOREIGN KEY ("CAR_BRAND_ID") REFERENCES  "CAR_BRAND" ("ID")
)

/
COMMIT
/

--//@UNDO

DROP TABLE CAR_BRAND
/
DROP TABLE CAR
/
DROP TABLE ADDRESS
/
DROP TABLE LOCATION
/
